Some tidy up and make it run under bash instead of sh.

diff --git a/bin/backup-system b/bin/backup-system
--- a/bin/backup-system
+++ b/bin/backup-system
@@ -1,22 +1,22 @@
-#!/bin/sh
+#!/bin/bash
 
 set -eux
 
+dt_start=$(date +%s)
+
 bkupdir="/backup"
 
-[ ${UID:-`id -u`} -ne 0 ] && {
-    echo Error: root privelidges required >&2
+[[ ${UID:-`id -u`} == 0 ]] || {
+    echo >&2 "Error: root privelidges required"
     exit 1
 }
 
-[ ! -d $bkupdir ] && {
-    echo Creating directory -- $bkupdir
-    mkdir -p $bkupdir || {
-        echo Error: problem creating directory -- $bkupdir >&2
-        exit 1
-    }
+[[ -d $bkupdir ]] || {
+    echo "Creating directory: $bkupdir"
+    mkdir -p $bkupdir || exit $?
 }
 
+umount /boot ||
 umount $bkupdir/boot ||
 umount $bkupdir ||
 true
@@ -37,13 +37,13 @@ rsync \
     --timeout=0 \
     --itemize-changes \
     --one-file-system \
-    --exclude="$bkupdir" \
     --exclude="/tmp/*" \
     --exclude="/run/*" \
     --exclude="/lost+found" \
     -F \
 / $bkupdir/
 
+mount /boot
 mount $bkupdir/boot
 
 rsync \
@@ -66,3 +66,12 @@ rsync \
 
 umount $bkupdir/boot
 umount $bkupdir
+umount /boot
+
+dt_end=$(date +%s)
+dt_time=$(( $dt_end - $dt_start ))
+
+dt_time_m=$(( $dt_time / 60 ))
+dt_time_s=$(( $dt_time % 60 ))
+
+echo "Completed backup in: $dt_time_m mins $dt_time_s secs"
